[target.armv7-linux-androideabi]
linker = "/mnt/ext/etc/android_sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi30-clang"

[target.aarch64-linux-android]
#linker = "/mnt/ext/etc/android_sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang"
linker = "/mnt/ext/etc/android_sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang"

[target.i686-linux-android]
linker = "/mnt/ext/etc/android_sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android30-clang"

[target.x86_64-linux-android]
#linker = "/mnt/ext/etc/android_sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android22-clang"
linker = "/mnt/ext/etc/android_sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android32-clang"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/cc"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"
#"/opt/riscv/bin/riscv64-unknown-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"


[build]
target = "x86_64-unknown-linux-gnu"
#target = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android", "riscv64gc-unknown-linux-gnu"]

target-dir = "./output"
